package com.ires.requirement.entity;

public enum RequirementStatus {
    DRAFT,
    SUBMITTED,
    IN_ANALYSIS,
    NEEDS_CLARIFICATION,
    ANALYSIS_COMPLETED,
    WAITING_FOR_ADMIN_ASSIGNMENT,
    ASSIGNED_TO_DEVELOPER,
    IN_DEVELOPMENT,
    READY_FOR_TESTING,
    ASSIGNED_TO_TESTER,
    IN_TESTING,
    TEST_FAILED,
    TEST_PASSED,
    WAITING_FOR_ADMIN_APPROVAL,
    COMPLETED
}
