import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import GlassCard from '../GlassCard.jsx'
import { requirementService } from '../../services/requirementService.js'
import { taskService } from '../../services/taskService.js'
import { getRequirementStatusLabel } from '../../config/requirementWorkflow.js'
import { date,Empty,Error,Status } from '../client/ClientProjects.jsx'
import { DeveloperHeader } from '../../pages/dashboards/DeveloperDashboard.jsx'
export default function DeveloperRequirements(){const [rows,setRows]=useState([]);const [error,setError]=useState('');useEffect(()=>{requirementService.listAccessible({size:100,sort:'updatedAt,desc'}).then(async(r)=>{const items=r.data.content||[];setRows(await Promise.all(items.map(async x=>{try{const t=(await taskService.list(x.projectId,{size:100})).data.content||[];const own=t.filter(v=>v.requirementId===x.id);return {...x,progress:`${own.filter(v=>v.status==='COMPLETED').length}/${own.length}`} }catch{return {...x,progress:'—'}}})))}).catch(e=>setError(e.message))},[]);return <><DeveloperHeader title="Assigned Requirements" subtitle="Requirements assigned to your authenticated Developer account."/>{error&&<Error message={error}/>} {!error&&rows.length===0&&<Empty message="No requirements are assigned to you."/>}{rows.length>0&&<div className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-white/[.06] text-xs uppercase text-slate-400"><tr>{['Requirement','Project','Client','Priority','Status','Developer','Updated','Task Progress','Action'].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-white/10"><td className="px-4 py-4 font-medium text-white">{r.title}</td><td className="px-4 py-4 text-slate-300">{r.projectName}</td><td className="px-4 py-4 text-slate-300">{r.projectClient?.name}</td><td className="px-4 py-4 text-slate-300">{r.priority}</td><td className="px-4 py-4"><Status value={getRequirementStatusLabel(r.status)}/></td><td className="px-4 py-4 text-slate-300">{r.assignedTo?.name}</td><td className="px-4 py-4 text-slate-400">{date(r.updatedAt)}</td><td className="px-4 py-4 text-slate-300">{r.progress}</td><td className="px-4 py-4"><Link className="text-blue-300" to={`/developer/requirements/${r.id}`}>Open</Link></td></tr>)}</tbody></table></div>}</>}
