import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import GlassCard from '../GlassCard.jsx'
import { requirementService } from '../../services/requirementService.js'
import { aiAnalysisService } from '../../services/aiAnalysisService.js'
import { acceptanceCriteriaService } from '../../services/acceptanceCriteriaService.js'
import { userStoryService } from '../../services/userStoryService.js'
import { traceabilityService } from '../../services/traceabilityService.js'
import { getRequirementStatusLabel } from '../../config/requirementWorkflow.js'
import { AnalystHeader } from '../../pages/dashboards/AnalystDashboard.jsx'
import { Area, date, Error, Field, Meta, Status } from '../client/ClientProjects.jsx'

export default function AnalystWorkspace() {
  const { id } = useParams(); const [data, setData] = useState(); const [error, setError] = useState(''); const [question, setQuestion] = useState(''); const [criterion, setCriterion] = useState({ title: '', description: '', criteriaType: 'FUNCTIONAL' }); const [story, setStory] = useState({ title: '', description: '', storyText: '', priority: 'MEDIUM' }); const [traceTarget, setTraceTarget] = useState('')
  const load = async () => { setError(''); try { const requirement = (await requirementService.get(id)).data; const calls = await Promise.all([requirementService.comments(id), requirementService.attachments(id), requirementService.clarifications(id), acceptanceCriteriaService.list(id, { size: 100 }), userStoryService.list(id, { size: 100 }), traceabilityService.list(id, { size: 100 }), aiAnalysisService.get(id).catch((e) => e.status === 404 ? null : Promise.reject(e))]); setData({ requirement, comments: calls[0].data.content || [], attachments: calls[1].data.content || [], clarifications: calls[2].data || [], criteria: calls[3].data.content || [], stories: calls[4].data.content || [], links: calls[5].data.content || [], ai: calls[6]?.data || null }) } catch (e) { setError(e.message) } }
  useEffect(() => { load() }, [id])
  if (error && !data) return <Error message={error} />; if (!data) return <GlassCard className="p-6"><p className="text-slate-400">Loading analysis workspace…</p></GlassCard>
  const { requirement: r } = data
  const act = async (action, body) => { const endpoint=action==='start-analysis'&&data.requirement.status==='NEEDS_CLARIFICATION'?'resume-analysis':action;try { await requirementService.action(id, endpoint, body); setQuestion(''); await load() } catch (e) { setError(e.message) } }
  const addCriterion = async (event) => { event.preventDefault(); try { await acceptanceCriteriaService.create(id, { ...criterion, status: 'DRAFT', userStoryId: null }); setCriterion({ title: '', description: '', criteriaType: 'FUNCTIONAL' }); await load() } catch (e) { setError(e.message) } }
  const editCriterion = async (item) => { const title = window.prompt('Criterion title', item.title); if (!title) return; try { await acceptanceCriteriaService.update(item.id, { userStoryId: item.userStoryId, title, description: item.description, criteriaType: item.criteriaType, status: item.status }); await load() } catch (e) { setError(e.message) } }
  const addStory = async (event) => { event.preventDefault(); try { await userStoryService.create(id, { ...story, status: 'DRAFT' }); setStory({ title: '', description: '', storyText: '', priority: 'MEDIUM' }); await load() } catch (e) { setError(e.message) } }
  const editStory = async (item) => { const storyText = window.prompt('User story text', item.storyText); if (!storyText) return; try { await userStoryService.update(item.id, { title: item.title, description: item.description, storyText, priority: item.priority, status: item.status }); await load() } catch (e) { setError(e.message) } }
  const addTrace = async () => { if (!traceTarget) return; const [targetType, targetId] = traceTarget.split(':'); try { await traceabilityService.createLink(id, { sourceType: 'REQUIREMENT', sourceId: id, targetType, targetId }); setTraceTarget(''); await load() } catch (e) { setError(e.message) } }
  const targets = [...data.criteria.map((v) => ({ value: `ACCEPTANCE_CRITERIA:${v.id}`, label: `Criterion: ${v.title}` })), ...data.stories.map((v) => ({ value: `USER_STORY:${v.id}`, label: `Story: ${v.title}` }))]
  const openClarification = data.clarifications.find((q) => q.status === 'OPEN'); const answered = data.clarifications.find((q) => q.status === 'RESPONDED')
  return <><AnalystHeader title={r.title} subtitle={`${r.projectName} · ${r.projectClient?.name || 'Client'}`} action={<Status value={getRequirementStatusLabel(r.status)} />} />{error && <Error message={error} />}
    <GlassCard hover={false} className="mb-6 p-6"><p className="whitespace-pre-wrap text-slate-300">{r.description || 'No description provided.'}</p><dl className="mt-5 grid gap-4 sm:grid-cols-4"><Meta label="Priority" value={r.priority} /><Meta label="Created" value={date(r.createdAt)} /><Meta label="Updated" value={date(r.updatedAt)} /><Meta label="Source" value={r.source || '—'} /></dl><div className="mt-6 flex flex-wrap gap-3">{r.status === 'SUBMITTED' && <button onClick={() => act('start-analysis')} className="btn-gradient">Start Analysis</button>}{r.status === 'IN_ANALYSIS' && <><button onClick={() => act('analysis-complete')} className="btn-gradient">Complete Analysis</button></>}{r.status === 'ANALYSIS_COMPLETED' && <button onClick={() => act('send-to-admin')} className="btn-gradient">Send to Admin</button>}{r.status === 'NEEDS_CLARIFICATION' && !openClarification && answered && <button onClick={() => act('start-analysis')} className="btn-gradient">Resume Analysis</button>}</div></GlassCard>
    <div className="grid gap-6 xl:grid-cols-2"><Section title="AI Suggestions"><button onClick={async () => { try { await aiAnalysisService.run(id); await load() } catch (e) { setError(e.message) } }} className="btn-outline mb-4 !py-2">{data.ai ? 'Run Again' : 'Run AI Analysis'}</button>{data.ai ? <div className="space-y-3 text-sm text-slate-300"><Status value={data.ai.analysisStatus} /><p>{data.ai.summary}</p><div className="grid grid-cols-3 gap-2"><Meta label="Ambiguity" value={data.ai.ambiguityScore ?? '—'} /><Meta label="Completeness" value={data.ai.completenessScore ?? '—'} /><Meta label="Quality" value={data.ai.qualityScore ?? '—'} /></div><p className="rounded-xl bg-white/[0.04] p-3">{data.ai.suggestions}</p></div> : <Muted text="No AI analysis has been run. Suggestions are advisory and never change workflow state." />}</Section>
      <Section title="Clarifications">{data.clarifications.map((q) => <div key={q.id} className="mb-3 rounded-xl border border-white/10 p-4"><p className="font-medium text-white">{q.question}</p><p className="mt-1 text-xs text-slate-500">{date(q.requestedAt)} · {q.status}</p>{q.response && <p className="mt-3 border-l-2 border-blue-400/40 pl-3 text-sm text-slate-300">{q.response} · {date(q.respondedAt)}</p>}</div>)}{data.clarifications.length === 0 && <Muted text="No clarification history." />}{r.status === 'IN_ANALYSIS' && !openClarification && <div className="mt-4"><Area label="Clarification question" value={question} onChange={setQuestion} /><button disabled={!question.trim()} onClick={() => act('request-clarification', { message: question })} className="btn-outline mt-3 !py-2">Request Clarification</button></div>}</Section>
      <Section title={`Acceptance Criteria (${data.criteria.length})`}>{data.criteria.map((item) => <Item key={item.id} title={item.title} detail={`${item.criteriaType} · ${item.status}`} onEdit={() => editCriterion(item)} onDelete={async () => { await acceptanceCriteriaService.remove(item.id); await load() }} />)}<form onSubmit={addCriterion} className="mt-4 space-y-3"><Field label="Criterion title" value={criterion.title} onChange={(title) => setCriterion({ ...criterion, title })} required /><Area label="Description" value={criterion.description} onChange={(description) => setCriterion({ ...criterion, description })} /><button className="btn-outline !py-2">Add Criterion</button></form></Section>
      <Section title={`User Stories (${data.stories.length})`}>{data.stories.map((item) => <Item key={item.id} title={item.title} detail={item.storyText} onEdit={() => editStory(item)} onDelete={async () => { await userStoryService.remove(item.id); await load() }} />)}<form onSubmit={addStory} className="mt-4 space-y-3"><Field label="Story title" value={story.title} onChange={(title) => setStory({ ...story, title })} required /><Area label="As a… I want… So that…" value={story.storyText} onChange={(storyText) => setStory({ ...story, storyText })} required /><button className="btn-outline !py-2">Add User Story</button></form></Section>
      <Section title={`Traceability Links (${data.links.length})`}>{data.links.map((link) => <Item key={link.id} title={`${link.sourceType} → ${link.targetType}`} detail={`${link.sourceId} → ${link.targetId}`} onDelete={async () => { await traceabilityService.removeLink(link.id); await load() }} />)}{targets.length ? <div className="mt-4 flex gap-2"><select value={traceTarget} onChange={(e) => setTraceTarget(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-space-900 px-3 py-2"><option value="">Link requirement to…</option>{targets.map((t) => <option key={t.value} value={t.value}>{t.label}</option>)}</select><button onClick={addTrace} className="btn-outline !px-3 !py-2">Add Link</button></div> : <Muted text="Create a criterion or user story before adding a traceability link." />}</Section>
      <Section title="Comments & Attachments"><h3 className="mb-2 text-sm font-semibold text-slate-300">Comments</h3>{data.comments.map((c) => <p key={c.id} className="mb-2 rounded-xl border border-white/10 p-3 text-sm text-slate-300">{c.comment} <span className="text-xs text-slate-500">— {c.author?.name}</span></p>)}{!data.comments.length && <Muted text="No comments." />}<h3 className="mb-2 mt-5 text-sm font-semibold text-slate-300">Attachments</h3>{data.attachments.map((a) => <p key={a.id} className="text-sm text-blue-300">{a.originalFileName}</p>)}{!data.attachments.length && <Muted text="No attachments." />}</Section></div>
  </>
}
function Section({ title, children }) { return <GlassCard hover={false} className="p-6"><h2 className="mb-4 text-lg font-semibold text-white">{title}</h2>{children}</GlassCard> }
function Item({ title, detail, onEdit, onDelete }) { return <div className="mb-2 rounded-xl border border-white/10 p-3"><div className="flex justify-between gap-3"><div><p className="text-sm font-medium text-white">{title}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div><div className="flex gap-2">{onEdit && <button onClick={onEdit} className="text-xs text-blue-300">Edit</button>}{onDelete && <button onClick={onDelete} className="text-xs text-red-300">Delete</button>}</div></div></div> }
function Muted({ text }) { return <p className="text-sm text-slate-500">{text}</p> }
