import { useEffect,useState } from 'react'
import { Navigate,Route,Routes,useLocation,useNavigate } from 'react-router-dom'
import { FileText,ListChecks,ClipboardCheck,Users,Bug } from 'lucide-react'
import DashboardLayout from '../../layouts/DashboardLayout.jsx';import GlassCard from '../../components/GlassCard.jsx';import StatCard from '../../components/StatCard.jsx';import ProfilePanel from '../../components/dashboard/ProfilePanel.jsx';import DeveloperRequirements from '../../components/developer/DeveloperRequirements.jsx';import DeveloperWorkspace from '../../components/developer/DeveloperWorkspace.jsx';import DeveloperLists from '../../components/developer/DeveloperLists.jsx';import { getRoleNavigation } from '../../config/roleNavigation.js';import { dashboardService } from '../../services/dashboardService.js'
import NotificationPage from '../../components/dashboard/NotificationPage.jsx'
const paths={overview:'/developer/dashboard',requirements:'/developer/requirements',tasks:'/developer/tasks',testCases:'/developer/test-cases',testerAssignment:'/developer/tester-assignment',bugs:'/developer/bugs',notifications:'/developer/notifications',profile:'/developer/profile'}
export default function DeveloperDashboard(){const nav=useNavigate(),loc=useLocation(),items=getRoleNavigation('DEVELOPER');const active=loc.pathname.startsWith('/developer/requirements/')?'requirements':Object.entries(paths).find(([,p])=>p===loc.pathname)?.[0]||'overview';return <DashboardLayout items={items} active={active} onSelect={k=>nav(paths[k])}><Routes><Route path="dashboard" element={<Overview/>}/><Route path="requirements" element={<DeveloperRequirements/>}/><Route path="requirements/:id" element={<DeveloperWorkspace/>}/><Route path="tasks" element={<DeveloperLists mode="tasks"/>}/><Route path="test-cases" element={<DeveloperLists mode="tests"/>}/><Route path="tester-assignment" element={<DeveloperLists mode="assignment"/>}/><Route path="bugs" element={<DeveloperLists mode="bugs"/>}/><Route path="notifications" element={<NotificationPage/>}/><Route path="profile" element={<><DeveloperHeader title="Profile" subtitle="Your authenticated Developer account."/><ProfilePanel/></>}/><Route path="*" element={<Navigate to="dashboard" replace/>}/></Routes></DashboardLayout>}
function Overview(){const[s,setS]=useState(null),[e,setE]=useState('');useEffect(()=>{dashboardService.getSummary().then(r=>setS(r.data)).catch(x=>setE(x.message))},[]);const icons=[FileText,ListChecks,ClipboardCheck,Users,Bug];return <><DeveloperHeader title="Developer Dashboard" subtitle="Assigned implementation work, quality preparation, and defects."/>{e&&<GlassCard className="p-6 text-red-300">{e}</GlassCard>}{!s&&!e&&<GlassCard className="p-6 text-slate-400">Loading dashboard…</GlassCard>}{s&&<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{s.metrics.map((m,i)=><StatCard key={m.key} icon={icons[i%icons.length]} label={m.label} value={m.value} delta={m.value===0?m.emptyMessage:undefined} index={i}/>)}</div>}</>}
export function DeveloperHeader({title,subtitle,action}){return <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><span className="text-xs font-semibold uppercase tracking-widest text-emerald-300">Developer</span><h1 className="text-2xl font-bold text-white sm:text-3xl">{title}</h1>{subtitle&&<p className="mt-1 text-sm text-slate-400">{subtitle}</p>}</div>{action}</div>}
function Placeholder({title}){return <><DeveloperHeader title={title}/><GlassCard hover={false} className="p-6 text-slate-400">Notifications will appear here when the notification backend is enabled.</GlassCard></>}
