package com.ires.notification.entity;

public enum NotificationType {
    REQUIREMENT_SUBMITTED, CLARIFICATION_REQUESTED, CLARIFICATION_RESPONDED,
    ANALYSIS_COMPLETED, DEVELOPER_ASSIGNED, TESTER_ASSIGNED,
    TEST_FAILED, TEST_PASSED, REQUIREMENT_COMPLETED, BUG_REPORTED
}
