ALTER TABLE requirements DROP CONSTRAINT ck_requirements_status;
ALTER TABLE requirements ALTER COLUMN status TYPE VARCHAR(40);

UPDATE requirements
SET status = CASE
    WHEN status = 'APPROVED_FOR_DEVELOPMENT' AND assigned_to IS NOT NULL THEN 'ASSIGNED_TO_DEVELOPER'
    WHEN status = 'APPROVED_FOR_DEVELOPMENT' THEN 'WAITING_FOR_ADMIN_ASSIGNMENT'
    WHEN status = 'FAILED' THEN 'TEST_FAILED'
    WHEN status = 'PASSED' THEN 'WAITING_FOR_ADMIN_APPROVAL'
    WHEN status = 'REJECTED' THEN 'NEEDS_CLARIFICATION'
    ELSE status
END;

ALTER TABLE requirements ADD CONSTRAINT ck_requirements_status CHECK (status IN (
    'DRAFT', 'SUBMITTED', 'IN_ANALYSIS', 'NEEDS_CLARIFICATION',
    'ANALYSIS_COMPLETED', 'WAITING_FOR_ADMIN_ASSIGNMENT',
    'ASSIGNED_TO_DEVELOPER', 'IN_DEVELOPMENT', 'READY_FOR_TESTING',
    'ASSIGNED_TO_TESTER', 'IN_TESTING', 'TEST_FAILED', 'TEST_PASSED',
    'WAITING_FOR_ADMIN_APPROVAL', 'COMPLETED'
));
