import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import GlassCard from '../GlassCard.jsx'
import { projectService } from '../../services/projectService.js'
import { requirementService } from '../../services/requirementService.js'
import { adminUserService } from '../../services/adminUserService.js'
import { acceptanceCriteriaService } from '../../services/acceptanceCriteriaService.js'
import { userStoryService } from '../../services/userStoryService.js'
import { aiAnalysisService } from '../../services/aiAnalysisService.js'
import { getRequirementStatusLabel } from '../../config/requirementWorkflow.js'
import { date, Empty, Error, Status } from '../client/ClientProjects.jsx'
import { AdminHeader } from '../../pages/dashboards/AdminDashboard.jsx'

export default function AdminRequirements({ assignmentQueue = false, finalQueue = false }) {
  const [requirements, setRequirements] = useState([]); const [projects, setProjects] = useState([]); const [users, setUsers] = useState([]); const [artifacts,setArtifacts]=useState({})
  const [filters, setFilters] = useState({ status: assignmentQueue ? 'WAITING_FOR_ADMIN_ASSIGNMENT' : finalQueue ? 'WAITING_FOR_ADMIN_APPROVAL' : '', projectId: '', clientId: '', priority: '', developerId: '', search: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([projectService.getProjects({ size: 100 }), adminUserService.getUsers()]).then(([p, u]) => { setProjects(p.data.content || []); setUsers(u.data || []) }).catch((e) => setError(e.message)) }, [])
  useEffect(() => { setLoading(true); const query = { size: 100, sort: 'updatedAt,desc', ...Object.fromEntries(Object.entries(filters).filter(([k, v]) => v && !['clientId', 'developerId'].includes(k))) }; requirementService.listAccessible(query).then(async(r) => { const items=r.data.content||[];setRequirements(items);if(assignmentQueue){const entries=await Promise.all(items.map(async(item)=>{const values=await Promise.allSettled([acceptanceCriteriaService.list(item.id,{size:1}),userStoryService.list(item.id,{size:1}),aiAnalysisService.get(item.id)]);return [item.id,{criteria:values[0].status==='fulfilled'?values[0].value.data.totalElements:0,stories:values[1].status==='fulfilled'?values[1].value.data.totalElements:0,ai:values[2].status==='fulfilled'}]}));setArtifacts(Object.fromEntries(entries))} }).catch((e) => setError(e.message)).finally(() => setLoading(false)) }, [assignmentQueue, filters.status, filters.projectId, filters.priority, filters.search])
  const visible = useMemo(() => requirements.filter((r) => (!filters.clientId || r.projectClient?.id === filters.clientId) && (!filters.developerId || r.assignedTo?.id === filters.developerId)), [requirements, filters.clientId, filters.developerId])
  const developers = users.filter((u) => u.role === 'DEVELOPER')
  return <><AdminHeader title={assignmentQueue ? 'Workflow / Assignments' : finalQueue ? 'Final Approval' : 'Requirements'} subtitle={assignmentQueue ? 'Analyzed requirements awaiting administrator review and developer assignment.' : finalQueue ? 'Test-passed requirements awaiting administrator completion review.' : 'System-wide requirements stored in PostgreSQL.'} />
    <GlassCard hover={false} className="mb-5 p-4"><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">
      {!assignmentQueue && !finalQueue && <Select value={filters.status} set={(status) => setFilters({ ...filters, status })}><option value="">All statuses</option>{statuses.map((v) => <option key={v}>{v}</option>)}</Select>}
      <Select value={filters.projectId} set={(projectId) => setFilters({ ...filters, projectId })}><option value="">All projects</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</Select>
      <Select value={filters.clientId} set={(clientId) => setFilters({ ...filters, clientId })}><option value="">All clients</option>{users.filter((u) => u.role === 'CLIENT').map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</Select>
      <Select value={filters.priority} set={(priority) => setFilters({ ...filters, priority })}><option value="">All priorities</option>{['LOW','MEDIUM','HIGH','CRITICAL'].map((v) => <option key={v}>{v}</option>)}</Select>
      {!assignmentQueue && <Select value={filters.developerId} set={(developerId) => setFilters({ ...filters, developerId })}><option value="">All developers</option>{developers.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</Select>}
      <input value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} placeholder="Search requirements" className="rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2.5 text-sm" />
    </div></GlassCard>
    {error && <Error message={error} />}{loading && <GlassCard hover={false} className="p-6 text-slate-400">Loading requirements…</GlassCard>}{!loading && !error && visible.length === 0 && <Empty message={assignmentQueue ? 'No requirements are awaiting developer assignment.' : finalQueue ? 'No requirements are awaiting final approval.' : 'No requirements match these filters.'} />}
    {!loading && visible.length > 0 && <div className="overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[1280px] text-left text-sm"><thead className="bg-white/[0.06] text-xs uppercase tracking-wide text-slate-400"><tr>{(assignmentQueue?['Requirement','Project','Client','Priority','Status','Analysis completed','Criteria','Stories','AI','Action']:['Requirement','Project','Client','Priority','Status','Analysis state','Assigned Developer','Created','Updated','Action']).map((h) => <th key={h} className={`px-4 py-3 ${h==='Action'?'sticky right-0 z-10 bg-space-900':''}`}>{h}</th>)}</tr></thead><tbody>{visible.map((r) => <tr key={r.id} className="border-t border-white/10 text-slate-300"><td className="px-4 py-4 font-medium text-white">{r.title}</td><td className="px-4 py-4">{r.projectName}</td><td className="px-4 py-4">{r.projectClient?.name || '—'}</td><td className="px-4 py-4">{r.priority}</td><td className="px-4 py-4"><Status value={getRequirementStatusLabel(r.status)} /></td>{assignmentQueue?<><td className="px-4 py-4">{date(r.updatedAt)}</td><td className="px-4 py-4">{artifacts[r.id]?.criteria??'…'}</td><td className="px-4 py-4">{artifacts[r.id]?.stories??'…'}</td><td className="px-4 py-4">{artifacts[r.id]?.ai?'Ready':'None'}</td></>:<><td className="px-4 py-4">{analysisLabel(r.status)}</td><td className="px-4 py-4">{r.assignedTo?.name || 'Unassigned'}</td><td className="px-4 py-4">{date(r.createdAt)}</td><td className="px-4 py-4">{date(r.updatedAt)}</td></>}<td className="sticky right-0 bg-space-900 px-4 py-4"><Link className="whitespace-nowrap text-blue-300 hover:text-blue-200" to={`/admin/requirements/${r.id}`}>{assignmentQueue ? 'Review & Assign' : 'Review'}</Link></td></tr>)}</tbody></table></div>}
  </>
}
const statuses = ['DRAFT','SUBMITTED','IN_ANALYSIS','NEEDS_CLARIFICATION','ANALYSIS_COMPLETED','WAITING_FOR_ADMIN_ASSIGNMENT','ASSIGNED_TO_DEVELOPER','IN_DEVELOPMENT','READY_FOR_TESTING','ASSIGNED_TO_TESTER','IN_TESTING','TEST_PASSED','TEST_FAILED','WAITING_FOR_ADMIN_APPROVAL','COMPLETED']
function analysisLabel(status) { return ['ANALYSIS_COMPLETED','WAITING_FOR_ADMIN_ASSIGNMENT','ASSIGNED_TO_DEVELOPER','IN_DEVELOPMENT','READY_FOR_TESTING','ASSIGNED_TO_TESTER','IN_TESTING','TEST_PASSED','TEST_FAILED','WAITING_FOR_ADMIN_APPROVAL','COMPLETED'].includes(status) ? 'Completed' : status === 'NEEDS_CLARIFICATION' ? 'Clarification' : status === 'IN_ANALYSIS' ? 'In progress' : 'Not completed' }
function Select({ value, set, children }) { return <select value={value} onChange={(e) => set(e.target.value)} className="rounded-xl border border-white/10 bg-space-900 px-3 py-2.5 text-sm">{children}</select> }
