import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import GlassCard from '../GlassCard.jsx'
import { requirementService } from '../../services/requirementService.js'
import { acceptanceCriteriaService } from '../../services/acceptanceCriteriaService.js'
import { userStoryService } from '../../services/userStoryService.js'
import { traceabilityService } from '../../services/traceabilityService.js'
import { aiAnalysisService } from '../../services/aiAnalysisService.js'
import { adminUserService } from '../../services/adminUserService.js'
import { taskService } from '../../services/taskService.js'
import { testCaseService } from '../../services/testCaseService.js'
import { bugService } from '../../services/bugService.js'
import { date, Error, Status } from '../client/ClientProjects.jsx'
import { getRequirementStatusLabel } from '../../config/requirementWorkflow.js'
import { AdminHeader } from '../../pages/dashboards/AdminDashboard.jsx'

export default function AdminRequirementReview() {
  const { id } = useParams(); const navigate = useNavigate(); const [data,setData]=useState(null); const [developers,setDevelopers]=useState([]); const [developerId,setDeveloperId]=useState(''); const [error,setError]=useState(''); const [assigning,setAssigning]=useState(false); const [completing,setCompleting]=useState(false)
  const load = async () => { setError(''); try { const requirement=(await requirementService.get(id)).data; const calls=await Promise.allSettled([requirementService.comments(id),requirementService.attachments(id),requirementService.clarifications(id),acceptanceCriteriaService.list(id,{size:100}),userStoryService.list(id,{size:100}),traceabilityService.list(id,{size:100}),aiAnalysisService.get(id),taskService.list(requirement.projectId,{size:100}),testCaseService.list(requirement.projectId,{size:100}),bugService.list(requirement.projectId,{size:100})]); const value=(index,fallback)=>calls[index].status==='fulfilled'?calls[index].value.data:fallback; const tests=(value(8,{content:[]}).content||[]).filter((x)=>x.requirementId===id); const executionCalls=await Promise.allSettled(tests.map((x)=>testCaseService.executions(x.id))); setData({requirement,comments:value(0,{content:[]}).content||[],attachments:value(1,{content:[]}).content||[],clarifications:value(2,[]),criteria:value(3,{content:[]}).content||[],stories:value(4,{content:[]}).content||[],links:value(5,{content:[]}).content||[],ai:value(6,null),tasks:(value(7,{content:[]}).content||[]).filter((x)=>x.requirementId===id),tests,executions:executionCalls.flatMap((x)=>x.status==='fulfilled'?(x.value.data||[]):[]),bugs:(value(9,{content:[]}).content||[]).filter((x)=>x.requirementId===id)}); if(requirement.status==='WAITING_FOR_ADMIN_ASSIGNMENT'){const eligible=(await adminUserService.getEligibleDevelopers(requirement.projectId)).data||[];setDevelopers(eligible);setDeveloperId(eligible[0]?.id||'')} } catch(e){setError(e.message) } }
  useEffect(()=>{load()},[id])
  const assign=async()=>{if(!developerId)return;setAssigning(true);setError('');try{await requirementService.action(id,'assign-developer',{developerId});await load()}catch(e){setError(e.message)}finally{setAssigning(false)}}
  const complete=async()=>{setCompleting(true);setError('');try{await requirementService.action(id,'complete',{});await load()}catch(e){setError(e.message)}finally{setCompleting(false)}}
  if(error&&!data)return <Error message={error}/>; if(!data)return <GlassCard hover={false} className="p-6 text-slate-400">Loading requirement review…</GlassCard>
  const r=data.requirement
  return <><AdminHeader title="Requirement Review" subtitle="Review the complete client and analyst package before development assignment." action={<Link to="/admin/workflow" className="btn-outline">Back to queue</Link>}/>{error&&<Error message={error}/>}<GlassCard hover={false} className="mb-5 p-6"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-semibold text-white">{r.title}</h2><p className="mt-2 max-w-4xl whitespace-pre-wrap text-slate-300">{r.description||'No description provided.'}</p></div><Status value={getRequirementStatusLabel(r.status)}/></div><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Meta label="Project" value={r.projectName}/><Meta label="Client" value={r.projectClient?.name}/><Meta label="Priority" value={r.priority}/><Meta label="Created" value={date(r.createdAt)}/><Meta label="Updated" value={date(r.updatedAt)}/></dl>{r.assignedTo&&<p className="mt-5 text-sm text-emerald-300">Assigned developer: {r.assignedTo.name} · {r.assignedTo.email}</p>}</GlassCard>
    {r.status==='WAITING_FOR_ADMIN_ASSIGNMENT'&&<GlassCard hover={false} className="mb-5 border-blue-400/20 p-6"><h3 className="font-semibold text-white">Assign Developer</h3><p className="mt-1 text-sm text-slate-400">Only active Developers who are already members of {r.projectName} are eligible.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><select value={developerId} onChange={(e)=>setDeveloperId(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-space-900 px-3 py-3"><option value="">Select an eligible Developer</option>{developers.map((d)=><option key={d.id} value={d.id}>{d.name} · {d.email}{d.username?` · ${d.username}`:''}</option>)}</select><button disabled={!developerId||assigning} onClick={assign} className="btn-gradient disabled:opacity-50">{assigning?'Assigning…':'Assign Developer'}</button></div>{developers.length===0&&<p className="mt-3 text-sm text-amber-300">No active Developer project members are currently eligible.</p>}</GlassCard>}
    {r.status==='WAITING_FOR_ADMIN_APPROVAL'&&<GlassCard hover={false} className="mb-5 border-emerald-400/20 p-6"><h3 className="font-semibold text-white">Final Approval</h3><p className="mt-1 text-sm text-slate-400">Completion is accepted only when every test case's latest execution passed and no open bug remains.</p><button disabled={completing} onClick={complete} className="btn-gradient mt-4 disabled:opacity-50">{completing?'Completing…':'Approve & Complete'}</button></GlassCard>}
    <div className="mb-5 grid gap-5 xl:grid-cols-2"><Section title={`Developer Tasks (${data.tasks.length})`}>{data.tasks.map((x)=><Item key={x.id} title={x.title} body={x.description} meta={`${x.status} · ${x.assignedTo?.name||'Unassigned'}`}/>)}</Section><Section title={`Test Cases (${data.tests.length})`}>{data.tests.map((x)=><Item key={x.id} title={x.title} body={x.expectedResult} meta={`${x.status} · ${x.assignedTo?.name||'Unassigned'}`}/>)}</Section><Section title={`Test Executions (${data.executions.length})`}>{data.executions.map((x)=><Item key={x.id} title={x.executionStatus} body={x.actualResult} meta={`${x.executedBy?.name||'Tester'} · ${date(x.executedAt)}`}/>)}</Section><Section title={`Bugs (${data.bugs.length})`}>{data.bugs.map((x)=><Item key={x.id} title={x.title} body={x.description} meta={`${x.severity} · ${x.status}`}/>)}</Section></div>
    <div className="grid gap-5 xl:grid-cols-2"><Section title={`Acceptance Criteria (${data.criteria.length})`}>{data.criteria.map((x)=><Item key={x.id} title={x.title} body={x.description} meta={`${x.criteriaType} · ${x.status}`}/>)}</Section><Section title={`User Stories (${data.stories.length})`}>{data.stories.map((x)=><Item key={x.id} title={x.title} body={x.storyText} meta={`${x.priority} · ${x.status}`}/>)}</Section><Section title="AI Analysis">{data.ai?<div className="space-y-3 text-sm text-slate-300"><Meta label="Status" value={data.ai.status}/><p className="whitespace-pre-wrap">{data.ai.summary||data.ai.suggestions||'Analysis is stored without a textual summary.'}</p></div>:<EmptyText text="No AI analysis is stored."/>}</Section><Section title={`Traceability (${data.links.length})`}>{data.links.map((x)=><Item key={x.id} title={`${x.sourceType} → ${x.targetType}`} body={`${x.sourceId} → ${x.targetId}`}/>)}</Section><Section title={`Clarifications (${data.clarifications.length})`}>{data.clarifications.map((x)=><Item key={x.id} title={x.question} body={x.response||'Awaiting response'} meta={x.status}/>)}</Section><Section title={`Comments & Attachments (${data.comments.length + data.attachments.length})`}>{data.comments.map((x)=><Item key={x.id} title={x.author?.name||'Comment'} body={x.comment}/>) }{data.attachments.map((x)=><Item key={x.id} title={x.originalFileName||x.fileName} meta="Attachment"/>)}</Section></div>
  </>
}
function Section({title,children}){return <GlassCard hover={false} className="p-5"><h3 className="mb-4 font-semibold text-white">{title}</h3><div className="space-y-3">{children?.length===0?<EmptyText text="None recorded."/>:children}</div></GlassCard>}
function Item({title,body,meta}){return <div className="rounded-xl border border-white/10 p-4"><p className="font-medium text-slate-100">{title}</p>{body&&<p className="mt-2 whitespace-pre-wrap text-sm text-slate-300">{body}</p>}{meta&&<p className="mt-2 text-xs text-slate-500">{meta}</p>}</div>}
function Meta({label,value}){return <div><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-200">{value||'—'}</dd></div>}
function EmptyText({text}){return <p className="text-sm text-slate-500">{text}</p>}
