import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import GlassCard from '../GlassCard.jsx'
import { projectService } from '../../services/projectService.js'
import { requirementService } from '../../services/requirementService.js'
import { getRequirementStatusLabel } from '../../config/requirementWorkflow.js'
import { ClientHeader } from '../../pages/dashboards/ClientDashboard.jsx'
import { date, Error, Meta, Status } from './ClientProjects.jsx'
import { deliveryUserService } from '../../services/deliveryUserService.js'

export default function ClientProjectDetail() {
  const { id } = useParams(); const [project, setProject] = useState(); const [requirements, setRequirements] = useState([]); const [members, setMembers] = useState([]); const [analysts, setAnalysts] = useState([]); const [analystId, setAnalystId] = useState(''); const [assigning, setAssigning] = useState(false); const [error, setError] = useState('')
  const load = async () => { setError(''); try { const [p,r,m,a]=await Promise.all([projectService.getProject(id),requirementService.list(id,'size=100&sort=createdAt,desc'),projectService.getProjectMembers(id),deliveryUserService.eligibleBusinessAnalysts(id)]);setProject(p.data);setRequirements(r.data?.content||[]);setMembers(m.data||[]);setAnalysts(a.data||[]);setAnalystId((a.data||[])[0]?.id||'') } catch(e){setError(e.message)} }
  useEffect(() => { load() }, [id])
  const assignAnalyst=async()=>{if(!analystId)return;setAssigning(true);setError('');try{await projectService.addProjectMember(id,{userId:analystId,projectRole:'BUSINESS_ANALYST'});await load()}catch(e){setError(e.message)}finally{setAssigning(false)}}
  if (error) return <Error message={error} />; if (!project) return <GlassCard className="p-6"><p className="text-slate-400">Loading project…</p></GlassCard>
  return <><ClientHeader title={project.name} subtitle="Project details and requirements." action={<Link className="btn-gradient !px-4 !py-2.5" to={`/client/requirements/new?projectId=${id}`}>Add Requirement</Link>} />
    <GlassCard hover={false} className="mb-6 p-6"><div className="flex justify-between gap-3"><p className="text-slate-300">{project.description || 'No description provided.'}</p><Status value={project.status} /></div><dl className="mt-5 grid gap-4 sm:grid-cols-3"><Meta label="Created" value={date(project.createdAt)} /><Meta label="Owner" value={project.client?.name} /><Meta label="Requirements" value={project.requirementCount ?? requirements.length} /></dl></GlassCard>
    <GlassCard hover={false} className="mb-6 p-6"><h2 className="text-lg font-semibold text-white">Business Analyst Access</h2><p className="mt-1 text-sm text-slate-400">Only assigned project-member Business Analysts can see submitted requirements in their queue.</p><div className="mt-4 space-y-2">{members.filter((member)=>member.projectRole==='BUSINESS_ANALYST').map((member)=><p key={member.id} className="text-sm text-slate-300">{member.user?.name||member.user?.email||'Business Analyst'}</p>)}{!members.some((member)=>member.projectRole==='BUSINESS_ANALYST')&&<p className="text-sm text-slate-500">No Business Analyst assigned.</p>}</div><div className="mt-4 flex flex-col gap-3 sm:flex-row"><select value={analystId} onChange={(e)=>setAnalystId(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-white/10 bg-space-900 px-3 py-3"><option value="">Select an eligible Business Analyst</option>{analysts.map((analyst)=><option key={analyst.id} value={analyst.id}>{analyst.name} · {analyst.email}</option>)}</select><button className="btn-gradient disabled:opacity-50" disabled={!analystId||assigning} onClick={assignAnalyst}>{assigning?'Assigning…':'Assign Analyst'}</button></div>{analysts.length===0&&<p className="mt-3 text-sm text-slate-500">No additional active Business Analysts are eligible.</p>}</GlassCard>
    <h2 className="mb-4 text-xl font-semibold text-white">Requirements</h2>{requirements.length === 0 ? <GlassCard className="p-6"><p className="text-slate-400">No requirements have been created for this project.</p></GlassCard> : <div className="space-y-3">{requirements.map((r) => <Link key={r.id} to={`/client/requirements/${r.id}`} className="glass block rounded-2xl p-5 transition hover:bg-white/[0.09]"><div className="flex justify-between gap-3"><div><h3 className="font-semibold text-white">{r.title}</h3><p className="mt-1 text-sm text-slate-400">{r.priority} priority</p></div><Status value={getRequirementStatusLabel(r.status)} /></div></Link>)}</div>}</>
}
