import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import GlassCard from '../GlassCard.jsx'
import FileDropzone from '../FileDropzone.jsx'
import { requirementService } from '../../services/requirementService.js'
import { getRequirementStatusLabel } from '../../config/requirementWorkflow.js'
import { ClientHeader } from '../../pages/dashboards/ClientDashboard.jsx'
import { Area, date, Error, Field, Meta, Status } from './ClientProjects.jsx'
import { Select } from './ClientRequirementForm.jsx'

export default function ClientRequirementDetail() {
  const { id } = useParams(); const [requirement, setRequirement] = useState(); const [comments, setComments] = useState([]); const [attachments, setAttachments] = useState([]); const [clarifications, setClarifications] = useState([]); const [error, setError] = useState(''); const [editing, setEditing] = useState(false); const [comment, setComment] = useState(''); const [response, setResponse] = useState(''); const [files, setFiles] = useState([])
  const load = async () => { setError(''); try { const [r, c, a, q] = await Promise.all([requirementService.get(id), requirementService.comments(id), requirementService.attachments(id), requirementService.clarifications(id)]); setRequirement(r.data); setComments(c.data.content || []); setAttachments(a.data.content || []); setClarifications(q.data || []) } catch (e) { setError(e.message) } }
  useEffect(() => { load() }, [id])
  if (error && !requirement) return <Error message={error} />; if (!requirement) return <GlassCard className="p-6"><p className="text-slate-400">Loading requirement…</p></GlassCard>
  const submit = async () => { try { await requirementService.action(id, 'submit'); await load() } catch (e) { setError(e.message) } }
  const saveEdit = async (form) => { try { await requirementService.update(id, { ...form, status: requirement.status, assignedTo: requirement.assignedTo?.id || null }); setEditing(false); await load() } catch (e) { setError(e.message) } }
  const addComment = async (event) => { event.preventDefault(); try { await requirementService.addComment(id, comment); setComment(''); await load() } catch (e) { setError(e.message) } }
  const respond = async (event) => { event.preventDefault(); try { await requirementService.action(id, 'clarifications', { message: response }); setResponse(''); await load() } catch (e) { setError(e.message) } }
  const upload = async () => { try { for (const file of files) await requirementService.uploadAttachment(id, file); setFiles([]); await load() } catch (e) { setError(e.message) } }
  const download = async (attachment) => { try { const blob = await requirementService.downloadAttachment(attachment.id); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = attachment.originalFileName; link.click(); URL.revokeObjectURL(url) } catch (e) { setError(e.message) } }
  return <><ClientHeader title={requirement.title} subtitle={`${requirement.projectName} · ${getRequirementStatusLabel(requirement.status)}`} action={requirement.status === 'DRAFT' && <div className="flex gap-2"><button onClick={() => setEditing((v) => !v)} className="btn-outline !px-4 !py-2.5">{editing ? 'Cancel' : 'Edit'}</button><button onClick={submit} className="btn-gradient !px-4 !py-2.5">Submit</button></div>} />{error && <Error message={error} />}
    {editing ? <EditForm requirement={requirement} onSave={saveEdit} /> : <GlassCard hover={false} className="mb-6 p-6"><div className="flex flex-wrap justify-between gap-3"><p className="max-w-3xl whitespace-pre-wrap text-slate-300">{requirement.description || 'No description provided.'}</p><Status value={getRequirementStatusLabel(requirement.status)} /></div><dl className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Meta label="Priority" value={requirement.priority} /><Meta label="Type" value={requirement.requirementType?.replaceAll('_', ' ')} /><Meta label="Created" value={date(requirement.createdAt)} /><Meta label="Last updated" value={date(requirement.updatedAt)} /></dl>{requirement.status === 'COMPLETED' && <p className="mt-5 rounded-xl border border-emerald-400/20 bg-emerald-500/10 p-4 text-emerald-200">This requirement has completed development, testing, and final approval.</p>}</GlassCard>}
    <div className="grid gap-6 xl:grid-cols-2"><Section title="Clarifications">{clarifications.length === 0 ? <Muted text="No clarification requests." /> : clarifications.map((q) => <div key={q.id} className="mb-3 rounded-xl border border-white/10 p-4"><p className="text-sm font-medium text-white">{q.question}</p><p className="mt-1 text-xs text-slate-500">Asked by {q.requestedBy?.name} · {date(q.requestedAt)}</p>{q.response && <div className="mt-3 border-l-2 border-blue-400/40 pl-3 text-sm text-slate-300">{q.response}</div>}</div>)}{requirement.status === 'NEEDS_CLARIFICATION' && clarifications.some((q) => q.status === 'OPEN') && <form onSubmit={respond}><Area label="Your response" value={response} onChange={setResponse} required /><button className="btn-gradient mt-3" disabled={!response.trim()}>Send Response</button></form>}</Section>
      <Section title="Attachments">{attachments.map((a) => <button key={a.id} onClick={() => download(a)} className="mb-2 block text-left text-sm text-blue-300 hover:text-blue-200">{a.originalFileName} <span className="text-slate-500">({Math.ceil(a.fileSize / 1024)} KB)</span></button>)}{attachments.length === 0 && <Muted text="No attachments." />}<div className="mt-4"><FileDropzone files={files} onChange={setFiles} />{files.length > 0 && <button onClick={upload} className="btn-outline mt-3 !py-2">Upload selected</button>}</div></Section>
      <Section title="Comments" wide>{comments.length === 0 && <Muted text="No comments yet." />}{comments.map((c) => <div key={c.id} className="mb-3 rounded-xl border border-white/10 p-4"><p className="text-sm text-slate-200">{c.comment}</p><p className="mt-2 text-xs text-slate-500">{c.author?.name} · {date(c.createdAt)}</p></div>)}<form onSubmit={addComment} className="mt-4"><Area label="Add comment" value={comment} onChange={setComment} required /><button disabled={!comment.trim()} className="btn-gradient mt-3">Add Comment</button></form></Section></div>
  </>
}

function EditForm({ requirement, onSave }) { const [form, setForm] = useState({ title: requirement.title, description: requirement.description || '', priority: requirement.priority, requirementType: requirement.requirementType, source: requirement.source || '' }); return <GlassCard hover={false} className="mb-6 p-6"><div className="space-y-4"><Field label="Title" value={form.title} onChange={(title) => setForm({ ...form, title })} required /><Area label="Description" value={form.description} onChange={(description) => setForm({ ...form, description })} /><div className="grid gap-4 sm:grid-cols-3"><Select label="Priority" value={form.priority} values={['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']} onChange={(priority) => setForm({ ...form, priority })} /><Select label="Type" value={form.requirementType} values={['FUNCTIONAL', 'NON_FUNCTIONAL', 'BUSINESS', 'TECHNICAL']} onChange={(requirementType) => setForm({ ...form, requirementType })} /><Field label="Source" value={form.source} onChange={(source) => setForm({ ...form, source })} /></div><button onClick={() => onSave(form)} className="btn-gradient">Save Changes</button></div></GlassCard> }
function Section({ title, children, wide }) { return <GlassCard hover={false} className={`p-6 ${wide ? 'xl:col-span-2' : ''}`}><h2 className="mb-4 text-lg font-semibold text-white">{title}</h2>{children}</GlassCard> }
function Muted({ text }) { return <p className="text-sm text-slate-500">{text}</p> }
