import { jsPDF } from 'jspdf'

export function generateSrsPdf({ projectName, requirements, userStories, traceability }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const margin = 48
  const pageWidth = doc.internal.pageSize.getWidth()
  const maxWidth = pageWidth - margin * 2
  let y = margin

  const addLine = (text, { size = 11, bold = false, gap = 16, color = '#111827' } = {}) => {
    if (y > 780) {
      doc.addPage()
      y = margin
    }
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setFontSize(size)
    doc.setTextColor(color)
    const lines = doc.splitTextToSize(text, maxWidth)
    doc.text(lines, margin, y)
    y += gap * lines.length
  }

  addLine('Software Requirements Specification', { size: 20, bold: true, gap: 26 })
  addLine(projectName, { size: 13, color: '#4f46e5', gap: 22 })
  addLine(`Generated by IRES AI on ${new Date().toLocaleDateString()}`, { size: 9, color: '#6b7280', gap: 24 })

  addLine('1. Requirements', { size: 14, bold: true, gap: 20 })
  requirements.forEach((r) => {
    addLine(`${r.id} — ${r.title}`, { size: 11, bold: true, gap: 15 })
    addLine(`Project: ${r.project}   Priority: ${r.priority}   Status: ${r.status}`, {
      size: 9,
      color: '#6b7280',
      gap: 18,
    })
  })

  addLine('2. User Stories & Acceptance Criteria', { size: 14, bold: true, gap: 20 })
  userStories.forEach((s) => {
    addLine(`${s.id} — ${s.title}`, { size: 11, bold: true, gap: 15 })
    s.acceptanceCriteria.forEach((ac) => addLine(`• ${ac}`, { size: 9.5, color: '#374151', gap: 14 }))
    y += 4
  })

  addLine('3. Traceability Matrix', { size: 14, bold: true, gap: 20 })
  traceability.forEach((t) => {
    addLine(
      `${t.requirement} → ${t.userStory} → ${t.testCase} → ${t.developer}`,
      { size: 9.5, color: '#374151', gap: 16 }
    )
  })

  return doc
}
